### ISSUE TITLE
Review Submission

### ISSUE THREAD

**Issue by not-xygen** [fzhnf/catppuccinWorld#1]
### Halo Faiz,

![image](https://github.com/fzhnf/catppuccinWorld/assets/73971391/d5a65f8c-1f0a-445e-bb97-516c0f243c0f)
Sorry but this is not the final :). You've got work to do.

Overall webnya bagus tapi ada beberapa kesalahan. Dalam struktur kode dan beberapa element placement yang kurang tepat.

1. Penggunaan `header` untuk dijadikan elemen penuh pada awal membuka website tidak tepat. `header` kamu cukup perlu seperti ini:
```html
<header>
 <h1>judul websitemu</h1>
</header>
```
untuk elemen `img`, `p`, `nav` bisa dipindah ke elemen baru. Jika ingin tetap layout sama akan dijelaskan dibawah, sebelumnya kita lanjut ke poin selanjutnya

2. Untuk struktur `main` lumayan meleset penggunaannya. Struktur yang benar adalah sebagai berikut:
```html
<main>
 <aside>...</aside>
 <div id="content">
  <section id="section1">...</section>
  <section id="section2">...</section>
  <section id="section3">...</section>  
 </div>
</main>
```
untuk elemen `article` yang ada di masing-masing `section`, bisa digabung di satu `section`. Sebagai contoh:
```html
<section id="section2">
 <article id="article1">...</article>
 <article id="article2">...</article>
 ....
</section>
```
nah, untuk konten yang harus dipindah dari `header`, bisa dimasukan ke `section1` dan juga bisa menghapus elemen `nav` jadi langsung seperti kode dibawah ini:
```html
<section id="section1">
 <img/>
 <p>...</p>
 <ul>...</ul>
</section>
```
Jika kamu tidak mau pindahin konten dari `header ke dalam section`, kamu bisa menggunakan opsi dibawah ini:
```html
<main>
 <div id="hero">
  <img/>
  <p>...</p>
  <ul>...</ul>
 </div>
 <div id="content-wrapper">
  <aside>...</aside>
  <div id="content">
  <section id="section1">...</section>
  <section id="section2">...</section>
  <section id="section3">...</section>  
 </div>
 </div>
</main>
```

3. `form` bisa dipindah dari `footer` ke `section3`.
```html
<section id="section3">
 <form>....</form>
</section>
```

Terimakasih atas pembuatan submissionnya. Jika sudah merevisi, segerakan upload kembali dan komen dibawah.

**Comment by fzhnf** [comment]
Sudah direvisi kak, sudah memenuhi  ketiga kriteria diatas :pray:
